// Seed data for the robotics tech marketplace

import { Technician } from './store';

export const seedTechnicians: Technician[] = [
  {
    id: 't_001',
    name: 'Aïcha Ben Salah',
    city: 'Paris',
    rating: 4.9,
    rate: 85,
    brands: ['LionsBot', 'Gaussian'],
    skills: ['Navigation', 'Battery Systems', 'Sensor Calibration'],
    bio: 'Senior robotics engineer with 8+ years in autonomous systems. Specialized in commercial cleaning robots.',
    photo: '/api/placeholder/400/400',
    availability: ['2025-09-14T10:00', '2025-09-14T14:00', '2025-09-15T09:00'],
    certifications: ['ROS Certified', 'AWS IoT Core', 'ISO 13482'],
    experience: '8 years',
    completedJobs: 147
  },
  {
    id: 't_002',
    name: 'Marcus Chen',
    city: 'Berlin',
    rating: 4.8,
    rate: 90,
    brands: ['Boston Dynamics', 'Agility'],
    skills: ['Locomotion', 'Computer Vision', 'AI Integration'],
    bio: 'Expert in bipedal and quadrupedal robots. Former Boston Dynamics engineer.',
    photo: '/api/placeholder/400/400',
    availability: ['2025-09-14T11:00', '2025-09-14T15:00', '2025-09-15T10:00'],
    certifications: ['Certified Robotics Engineer', 'Machine Learning Professional'],
    experience: '6 years',
    completedJobs: 89
  },
  {
    id: 't_003',
    name: 'Sofia Rodriguez',
    city: 'Madrid',
    rating: 4.7,
    rate: 75,
    brands: ['Universal Robots', 'KUKA'],
    skills: ['Industrial Automation', 'PLC Programming', 'Safety Systems'],
    bio: 'Industrial robotics specialist with focus on manufacturing automation.',
    photo: '/api/placeholder/400/400',
    availability: ['2025-09-14T12:00', '2025-09-14T16:00', '2025-09-15T08:00'],
    certifications: ['KUKA Certified', 'UR Academy Graduate'],
    experience: '10 years',
    completedJobs: 203
  },
  {
    id: 't_004',
    name: 'David Kim',
    city: 'London',
    rating: 4.9,
    rate: 95,
    brands: ['Spot', 'ANYmal'],
    skills: ['Inspection Robotics', 'Remote Operations', 'Data Analytics'],
    bio: 'Specializes in inspection robots for construction and energy sectors.',
    photo: '/api/placeholder/400/400',
    availability: ['2025-09-14T13:00', '2025-09-15T11:00', '2025-09-15T15:00'],
    certifications: ['Spot Operator', 'Drone Pilot License'],
    experience: '5 years',
    completedJobs: 76
  },
  {
    id: 't_005',
    name: 'Elena Volkov',
    city: 'Amsterdam',
    rating: 4.6,
    rate: 80,
    brands: ['Clearpath', 'Fetch'],
    skills: ['Warehouse Automation', 'Fleet Management', 'SLAM'],
    bio: 'Warehouse robotics expert helping businesses optimize their logistics.',
    photo: '/api/placeholder/400/400',
    availability: ['2025-09-14T09:00', '2025-09-14T14:30', '2025-09-15T12:00'],
    certifications: ['AWS Robotics', 'Fetch Certified'],
    experience: '7 years',
    completedJobs: 134
  },
  {
    id: 't_006',
    name: 'James Thompson',
    city: 'Dublin',
    rating: 4.8,
    rate: 70,
    brands: ['iRobot', 'Neato'],
    skills: ['Consumer Robotics', 'Maintenance', 'Troubleshooting'],
    bio: 'Consumer robotics technician specializing in home automation systems.',
    photo: '/api/placeholder/400/400',
    availability: ['2025-09-14T08:00', '2025-09-14T17:00', '2025-09-15T13:00'],
    certifications: ['iRobot Certified', 'Home Assistant Expert'],
    experience: '4 years',
    completedJobs: 92
  },
  {
    id: 't_007',
    name: 'Yuki Tanaka',
    city: 'Barcelona',
    rating: 4.9,
    rate: 100,
    brands: ['Honda', 'Toyota'],
    skills: ['Humanoid Robotics', 'Actuator Systems', 'Biped Walking'],
    bio: 'Former Honda ASIMO team member, now freelance humanoid robotics consultant.',
    photo: '/api/placeholder/400/400',
    availability: ['2025-09-14T10:30', '2025-09-15T09:30', '2025-09-15T14:00'],
    certifications: ['Honda Certified', 'IEEE Robotics Fellow'],
    experience: '12 years',
    completedJobs: 45
  },
  {
    id: 't_008',
    name: 'Anna Mueller',
    city: 'Munich',
    rating: 4.7,
    rate: 85,
    brands: ['ABB', 'Fanuc'],
    skills: ['Collaborative Robots', 'Human-Robot Interaction', 'Safety'],
    bio: 'Cobot integration specialist making robots safe for human collaboration.',
    photo: '/api/placeholder/400/400',
    availability: ['2025-09-14T11:30', '2025-09-14T16:30', '2025-09-15T10:30'],
    certifications: ['ABB Certified', 'ISO 10218 Expert'],
    experience: '9 years',
    completedJobs: 156
  },
  {
    id: 't_009',
    name: 'Lucas Silva',
    city: 'Lisbon',
    rating: 4.5,
    rate: 65,
    brands: ['DJI', 'Parrot'],
    skills: ['Aerial Robotics', 'Surveillance', 'Mapping'],
    bio: 'Drone and aerial robotics specialist for surveillance and mapping projects.',
    photo: '/api/placeholder/400/400',
    availability: ['2025-09-14T07:00', '2025-09-14T15:30', '2025-09-15T11:30'],
    certifications: ['Part 107 Pilot', 'DJI Certified'],
    experience: '3 years',
    completedJobs: 67
  },
  {
    id: 't_010',
    name: 'Priya Sharma',
    city: 'Brussels',
    rating: 4.8,
    rate: 90,
    brands: ['Waymo', 'Tesla'],
    skills: ['Autonomous Vehicles', 'LiDAR', 'Path Planning'],
    bio: 'Autonomous vehicle systems engineer with expertise in self-driving technologies.',
    photo: '/api/placeholder/400/400',
    availability: ['2025-09-14T12:30', '2025-09-15T08:30', '2025-09-15T16:00'],
    certifications: ['ADAS Certified', 'LiDAR Specialist'],
    experience: '6 years',
    completedJobs: 78
  }
];