import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  fr: {
    // Landing page
    'landing.trusted': '🤖 Approuvé par 500+ Entreprises',
    'landing.hero.title': 'Réservez des Techniciens Robotiques Certifiés',
    'landing.hero.subtitle': 'N\'importe quand, N\'importe où. Connectez-vous avec des techniciens robotiques experts pour la maintenance, le dépannage et l\'optimisation système. Réservez instantanément comme chez le coiffeur.',
    'landing.hero.findTech': 'Trouver un Technicien',
    'landing.hero.becomeTech': 'Devenir un Technicien Robotique Certifié',
    'landing.stats.technicians': 'Techniciens',
    'landing.stats.response': 'Réponse Moy.',
    'landing.stats.success': 'Taux de Réussite',
    'landing.featured.title': 'Les Plus Réservés Cette Semaine',
    'landing.featured.subtitle': 'Rencontrez nos techniciens robotiques les mieux notés, approuvés par les entreprises leaders',
    'landing.featured.bookNow': 'Réserver Maintenant',
    'landing.howItWorks.title': 'Simple comme 1-2-3',
    'landing.howItWorks.subtitle': 'Réservez un support robotique expert en quelques minutes',
    'landing.howItWorks.step1.title': 'Parcourir et Filtrer',
    'landing.howItWorks.step1.desc': 'Trouvez des techniciens par localisation, marque de robot et expertise',
    'landing.howItWorks.step2.title': 'Réserver Instantanément',
    'landing.howItWorks.step2.desc': 'Choisissez votre créneau horaire et confirmez votre réservation en quelques secondes',
    'landing.howItWorks.step3.title': 'Obtenir de l\'Aide',
    'landing.howItWorks.step3.desc': 'Chattez avec votre technicien et suivez les progrès en temps réel',
    
    // Catalog page
    'catalog.title': 'Trouver un Technicien',
    'catalog.available': 'techniciens disponibles',
    'catalog.filters': 'Filtres',
    'catalog.clearAll': 'Tout effacer',
    'catalog.search': 'Rechercher',
    'catalog.searchPlaceholder': 'Nom, compétences ou mots-clés...',
    'catalog.location': 'Localisation',
    'catalog.allLocations': 'Toutes les localisations',
    'catalog.robotBrands': 'Marques de Robots',
    'catalog.minRating': 'Note Minimale',
    'catalog.anyRating': 'Toute note',
    'catalog.stars': 'étoiles',
    'catalog.activeFilters': 'Filtres Actifs',
    'catalog.noResults': 'Aucun technicien trouvé',
    'catalog.noResultsDesc': 'Essayez d\'ajuster vos filtres ou termes de recherche',
    'catalog.clearFilters': 'Effacer les Filtres',
    
    // Profile page
    'profile.notFound': 'Technicien introuvable',
    'profile.backToCatalog': 'Retour au Catalogue',
    'profile.roboticsTechnician': 'Technicien Robotique',
    'profile.availableToday': 'Disponible Aujourd\'hui',
    'profile.startingRate': 'Tarif de départ',
    'profile.experience': 'expérience',
    'profile.about': 'À Propos',
    'profile.certifications': 'Certifications',
    'profile.skillsExpertise': 'Compétences et Expertise',
    'profile.robotBrands': 'Marques de Robots',
    'profile.technicalSkills': 'Compétences Techniques',
    'profile.recentReviews': 'Avis Récents',
    'profile.book': 'Réserver',
    'profile.availableTimes': 'Heures Disponibles',
    'profile.bookNow': 'Réserver Maintenant',
    'profile.sendMessage': 'Envoyer un Message',
    'profile.responseTime': 'Temps de Réponse',
    'profile.usuallyResponds': 'Répond généralement en 15 minutes',
    'profile.veryResponsive': 'Très réactif',
    
    // Booking Form
    'booking.title': 'Réserver',
    'booking.completeBooking': 'Complétez votre réservation',
    'booking.bookingDetails': 'Détails de la Réservation',
    'booking.yourInfo': 'Vos Informations',
    'booking.fullName': 'Nom Complet',
    'booking.fullNamePlaceholder': 'Entrez votre nom complet',
    'booking.dateTime': 'Date et Heure',
    'booking.date': 'Date',
    'booking.time': 'Heure',
    'booking.selectTime': 'Sélectionner l\'heure',
    'booking.serviceLocation': 'Lieu du Service',
    'booking.address': 'Adresse',
    'booking.addressPlaceholder': 'Entrez l\'adresse du lieu de service',
    'booking.jobDetails': 'Détails du Travail',
    'booking.estimatedDuration': 'Durée Estimée (heures)',
    'booking.hour': 'heure',
    'booking.hours': 'heures',
    'booking.additionalNotes': 'Notes Supplémentaires',
    'booking.notesPlaceholder': 'Décrivez le problème, modèle de robot, exigences spécifiques...',
    'booking.confirmBooking': 'Confirmer la Réservation',
    'booking.yourTechnician': 'Votre Technicien',
    'booking.jobs': 'travaux',
    'booking.priceSummary': 'Résumé des Prix',
    'booking.hourlyRate': 'Tarif horaire',
    'booking.duration': 'Durée',
    'booking.total': 'Total',
    'booking.priceNote': '💡 Le prix final peut varier selon le temps réel passé et les matériaux utilisés',
    'booking.whyBookWithUs': 'Pourquoi réserver avec nous ?',
    'booking.vettedProfessionals': 'Professionnels vérifiés',
    'booking.securePayment': 'Paiement sécurisé',
    'booking.support247': 'Support 24/7',
    'booking.moneyBackGuarantee': 'Garantie de remboursement',
    
    // Confirmation page
    'confirmation.title': 'Réservation Confirmée',
    'confirmation.subtitle': 'Votre technicien robotique est en route',
    'confirmation.bookingConfirmed': 'Réservation Confirmée !',
    'confirmation.successMessage': 'Votre technicien robotique a été réservé avec succès. Vous recevrez un e-mail de confirmation sous peu.',
    'confirmation.paymentSecured': '🔒 Paiement Sécurisé',
    'confirmation.bookingDetails': 'Détails de la Réservation',
    'confirmation.rating': 'note',
    'confirmation.jobsCompleted': 'travaux terminés',
    'confirmation.dateTime': 'Date et Heure',
    'confirmation.location': 'Localisation',
    'confirmation.serviceNotes': 'Notes de Service',
    'confirmation.paymentSecuredTitle': 'Paiement Sécurisé',
    'confirmation.paymentNote': 'Le paiement sera traité après la fin du service',
    'confirmation.message': 'Message',
    'confirmation.callSupport': 'Appeler le Support',
    'confirmation.addToCalendar': 'Ajouter au Calendrier',
    'confirmation.whatHappensNext': 'Que se passe-t-il ensuite ?',
    'confirmation.techWillContact': 'Le technicien vous contactera',
    'confirmation.techWillContactDesc': 'vous contactera dans les 30 minutes pour confirmer les détails',
    'confirmation.serviceAppointment': 'Rendez-vous de service',
    'confirmation.serviceAppointmentDesc': 'Votre technicien arrivera à l\'heure prévue',
    'confirmation.paymentReview': 'Paiement et avis',
    'confirmation.paymentReviewDesc': 'Complétez le paiement et laissez un avis après le service',
    'confirmation.supportInfo': 'Besoin d\'aide ? Contactez notre équipe de support 24/7 à support@robomatch.com ou +1 (555) 123-4567',
    
    // Messages page
    'messages.notFound': 'Conversation introuvable',
    'messages.backToHome': 'Retour à l\'Accueil',
    'messages.online': '● En ligne',
    'messages.call': 'Appeler',
    'messages.bookingDetails': 'Détails de la Réservation',
    'messages.total': 'total',
    'messages.typePlaceholder': 'Tapez un message...',
    'messages.arrivalTime': '📅 Heure d\'arrivée ?',
    'messages.needInfo': '❓ Besoin d\'infos ?',
    'messages.reschedule': '🔄 Reprogrammer',
    'messages.thankYou': '🙏 Merci',
    
    // Bootcamp page
    'bootcamp.backToHome': 'Retour à l\'Accueil',
    'bootcamp.careerProgram': '🎓 Programme de Transformation de Carrière',
    'bootcamp.title': 'Bienvenue dans Votre Nouvelle Carrière',
    'bootcamp.subtitle': 'Rejoignez notre bootcamp de 2 semaines à €900 aujourd\'hui pour seulement €500. Devenez un technicien robotique certifié et soyez libre de choisir quand vous travaillez, comment vous travaillez, et gagnez jusqu\'à €5 000 par mois.',
    'bootcamp.enrollNow': 'S\'inscrire Maintenant - €500',
    'bootcamp.save': 'Économisez €400 !',
    'bootcamp.duration': 'Durée',
    'bootcamp.monthlyPotential': 'Potentiel Mensuel',
    'bootcamp.jobReady': 'Prêt à Travailler',
    'bootcamp.courseTitle': 'Formation de Technicien Robotique de Terrain – Niveau 1',
    'bootcamp.courseSubtitle': 'Maîtrisez les compétences nécessaires pour travailler avec des robots de service autonomes et lancez votre carrière freelance',
    'bootcamp.objectives': 'Objectifs du Cours',
    'bootcamp.readyToStart': 'Prêt à Commencer Votre Parcours ?',
    'bootcamp.graduatesEarning': 'Rejoignez des centaines de diplômés qui gagnent maintenant €3 000-€5 000 mensuellement en tant que techniciens robotiques freelance.',
    'bootcamp.secureSpot': 'Réservez Votre Place - €500',
    'bootcamp.limitedOffer': 'Offre limitée. Prix normal €900.',
    
    // TechCard component
    'techCard.available': 'Disponible',
    'techCard.experience': 'expérience',
    'techCard.more': 'plus',
    'techCard.skills': 'compétences',
    'techCard.jobsCompleted': 'travaux terminés',
    'techCard.startingAt': 'À partir de',
    'techCard.viewProfile': 'Voir le Profil',
    'techCard.bookNow': 'Réserver',
    
    // Traductions d'inscription
    'registration.title': 'Créez Votre Compte Technicien',
    'registration.subtitle': 'Rejoignez le réseau de techniciens robotiques certifiés',
    'registration.backToBootcamp': 'Retour au Bootcamp',
    'registration.personalInfo': 'Informations Personnelles',
    'registration.firstName': 'Prénom',
    'registration.lastName': 'Nom',
    'registration.email': 'Adresse Email',
    'registration.phone': 'Numéro de Téléphone',
    'registration.city': 'Ville',
    'registration.technicalBackground': 'Formation Technique',
    'registration.currentField': 'Domaine Technique Actuel',
    'registration.techBackgroundPlaceholder': 'Décrivez votre expérience technique actuelle (automobile, électronique, mécanique, etc.)',
    'registration.experience': 'Années d\'Expérience Technique',
    'registration.selectExperience': 'Sélectionnez votre niveau',
    'registration.experienceOptions.beginner': '0-1 ans (Débutant)',
    'registration.experienceOptions.intermediate': '2-5 ans (Intermédiaire)',
    'registration.experienceOptions.experienced': '5-10 ans (Expérimenté)',
    'registration.experienceOptions.expert': '10+ ans (Expert)',
    'registration.requirements': 'Prérequis',
    'registration.canDrive': 'J\'ai un permis de conduire valide',
    'registration.freelancerStatus': 'J\'ai le statut de freelance (auto-entrepreneur, micro-entreprise, etc.)',
    'registration.taxNumber': 'J\'ai un numéro d\'identification fiscale',
    'registration.bio': 'Biographie Professionnelle (Optionnel)',
    'registration.bioPlaceholder': 'Parlez aux clients de votre expertise et de ce qui vous rend unique...',
    'registration.createAccount': 'Créer un Compte & Continuer vers le Bootcamp',
    'registration.terms': 'En créant un compte, vous acceptez nos Conditions d\'Utilisation et notre Politique de Confidentialité',
    'registration.errors.required': 'Ce champ est obligatoire',
    'registration.errors.freelancerRequired': 'Le statut de freelance est requis pour rejoindre notre plateforme',
  },
  en: {
    // Landing page
    'landing.trusted': '🤖 Trusted by 500+ Companies',
    'landing.hero.title': 'Book Certified Robotics Technicians',
    'landing.hero.subtitle': 'Anytime, Anywhere. Connect with expert robotics technicians for maintenance, troubleshooting, and system optimization. Book instantly like a haircut.',
    'landing.hero.findTech': 'Find a Technician',
    'landing.hero.becomeTech': 'Become a Certified Robotics Tech',
    'landing.stats.technicians': 'Technicians',
    'landing.stats.response': 'Avg Response',
    'landing.stats.success': 'Success Rate',
    'landing.featured.title': 'Most Booked This Week',
    'landing.featured.subtitle': 'Meet our top-rated robotics technicians trusted by leading companies',
    'landing.featured.bookNow': 'Book Now',
    'landing.howItWorks.title': 'Simple as 1-2-3',
    'landing.howItWorks.subtitle': 'Book expert robotics support in minutes',
    'landing.howItWorks.step1.title': 'Browse & Filter',
    'landing.howItWorks.step1.desc': 'Find technicians by location, robot brand, and expertise',
    'landing.howItWorks.step2.title': 'Book Instantly',
    'landing.howItWorks.step2.desc': 'Choose your time slot and confirm your booking in seconds',
    'landing.howItWorks.step3.title': 'Get Support',
    'landing.howItWorks.step3.desc': 'Chat with your technician and track progress in real-time',
    
    // Catalog page
    'catalog.title': 'Find a Technician',
    'catalog.available': 'technicians available',
    'catalog.filters': 'Filters',
    'catalog.clearAll': 'Clear all',
    'catalog.search': 'Search',
    'catalog.searchPlaceholder': 'Name, skills, or keywords...',
    'catalog.location': 'Location',
    'catalog.allLocations': 'All locations',
    'catalog.robotBrands': 'Robot Brands',
    'catalog.minRating': 'Minimum Rating',
    'catalog.anyRating': 'Any rating',
    'catalog.stars': 'stars',
    'catalog.activeFilters': 'Active Filters',
    'catalog.noResults': 'No technicians found',
    'catalog.noResultsDesc': 'Try adjusting your filters or search terms',
    'catalog.clearFilters': 'Clear Filters',
    
    // Profile page
    'profile.notFound': 'Technician not found',
    'profile.backToCatalog': 'Back to Catalog',
    'profile.roboticsTechnician': 'Robotics Technician',
    'profile.availableToday': 'Available Today',
    'profile.startingRate': 'Starting rate',
    'profile.experience': 'experience',
    'profile.about': 'About',
    'profile.certifications': 'Certifications',
    'profile.skillsExpertise': 'Skills & Expertise',
    'profile.robotBrands': 'Robot Brands',
    'profile.technicalSkills': 'Technical Skills',
    'profile.recentReviews': 'Recent Reviews',
    'profile.book': 'Book',
    'profile.availableTimes': 'Available Times',
    'profile.bookNow': 'Book Now',
    'profile.sendMessage': 'Send Message',
    'profile.responseTime': 'Response Time',
    'profile.usuallyResponds': 'Usually responds in 15 minutes',
    'profile.veryResponsive': 'Very responsive',
    
    // Booking Form
    'booking.title': 'Book',
    'booking.completeBooking': 'Complete your booking',
    'booking.bookingDetails': 'Booking Details',
    'booking.yourInfo': 'Your Information',
    'booking.fullName': 'Full Name',
    'booking.fullNamePlaceholder': 'Enter your full name',
    'booking.dateTime': 'Date & Time',
    'booking.date': 'Date',
    'booking.time': 'Time',
    'booking.selectTime': 'Select time',
    'booking.serviceLocation': 'Service Location',
    'booking.address': 'Address',
    'booking.addressPlaceholder': 'Enter the service location address',
    'booking.jobDetails': 'Job Details',
    'booking.estimatedDuration': 'Estimated Duration (hours)',
    'booking.hour': 'hour',
    'booking.hours': 'hours',
    'booking.additionalNotes': 'Additional Notes',
    'booking.notesPlaceholder': 'Describe the issue, robot model, any specific requirements...',
    'booking.confirmBooking': 'Confirm Booking',
    'booking.yourTechnician': 'Your Technician',
    'booking.jobs': 'jobs',
    'booking.priceSummary': 'Price Summary',
    'booking.hourlyRate': 'Hourly rate',
    'booking.duration': 'Duration',
    'booking.total': 'Total',
    'booking.priceNote': '💡 Final price may vary based on actual time spent and materials used',
    'booking.whyBookWithUs': 'Why book with us?',
    'booking.vettedProfessionals': 'Vetted professionals',
    'booking.securePayment': 'Secure payment',
    'booking.support247': '24/7 support',
    'booking.moneyBackGuarantee': 'Money-back guarantee',
    
    // Confirmation page
    'confirmation.title': 'Booking Confirmed',
    'confirmation.subtitle': 'Your robotics technician is on the way',
    'confirmation.bookingConfirmed': 'Booking Confirmed!',
    'confirmation.successMessage': 'Your robotics technician has been successfully booked. You\'ll receive a confirmation email shortly.',
    'confirmation.paymentSecured': '🔒 Payment Secured',
    'confirmation.bookingDetails': 'Booking Details',
    'confirmation.rating': 'rating',
    'confirmation.jobsCompleted': 'jobs completed',
    'confirmation.dateTime': 'Date & Time',
    'confirmation.location': 'Location',
    'confirmation.serviceNotes': 'Service Notes',
    'confirmation.paymentSecuredTitle': 'Payment Secured',
    'confirmation.paymentNote': 'Payment will be processed after service completion',
    'confirmation.message': 'Message',
    'confirmation.callSupport': 'Call Support',
    'confirmation.addToCalendar': 'Add to Calendar',
    'confirmation.whatHappensNext': 'What happens next?',
    'confirmation.techWillContact': 'Technician will contact you',
    'confirmation.techWillContactDesc': 'will reach out within 30 minutes to confirm details',
    'confirmation.serviceAppointment': 'Service appointment',
    'confirmation.serviceAppointmentDesc': 'Your technician will arrive at the scheduled time',
    'confirmation.paymentReview': 'Payment & review',
    'confirmation.paymentReviewDesc': 'Complete payment and leave a review after the service',
    'confirmation.supportInfo': 'Need help? Contact our support team 24/7 at support@robomatch.com or +1 (555) 123-4567',
    
    // Messages page
    'messages.notFound': 'Conversation not found',
    'messages.backToHome': 'Back to Home',
    'messages.online': '● Online',
    'messages.call': 'Call',
    'messages.bookingDetails': 'Booking Details',
    'messages.total': 'total',
    'messages.typePlaceholder': 'Type a message...',
    'messages.arrivalTime': '📅 Arrival time?',
    'messages.needInfo': '❓ Need info?',
    'messages.reschedule': '🔄 Reschedule',
    'messages.thankYou': '🙏 Thank you',
    
    // Bootcamp page
    'bootcamp.backToHome': 'Back to Home',
    'bootcamp.careerProgram': '🎓 Career Transformation Program',
    'bootcamp.title': 'Welcome to Your New Career',
    'bootcamp.subtitle': 'Join our €900 2-week bootcamp today for just €500. Become a certified robotics technician and be free to choose when you work, how you work, and make up to €5,000 per month.',
    'bootcamp.enrollNow': 'Enroll Now - €500',
    'bootcamp.save': 'Save €400!',
    'bootcamp.duration': 'Duration',
    'bootcamp.monthlyPotential': 'Monthly Potential',
    'bootcamp.jobReady': 'Job Ready',
    'bootcamp.courseTitle': 'Field Robotics Technician Training – Level 1',
    'bootcamp.courseSubtitle': 'Master the skills needed to work with autonomous service robots and launch your freelance career',
    'bootcamp.objectives': 'Course Objectives',
    'bootcamp.readyToStart': 'Ready to Start Your Journey?',
    'bootcamp.graduatesEarning': 'Join hundreds of successful graduates who are now earning €3,000-€5,000 monthly as freelance robotics technicians.',
    'bootcamp.secureSpot': 'Secure Your Spot - €500',
    'bootcamp.limitedOffer': 'Limited time offer. Regular price €900.',
    
    // TechCard component
    'techCard.available': 'Available',
    'techCard.experience': 'experience',
    'techCard.more': 'more',
    'techCard.skills': 'skills',
    'techCard.jobsCompleted': 'jobs completed',
    'techCard.startingAt': 'Starting at',
    'techCard.viewProfile': 'View Profile',
    'techCard.bookNow': 'Book Now',
    
    // Registration translations
    'registration.title': 'Create Your Technician Account',
    'registration.subtitle': 'Join the certified robotics technician network',
    'registration.backToBootcamp': 'Back to Bootcamp',
    'registration.personalInfo': 'Personal Information',
    'registration.firstName': 'First Name',
    'registration.lastName': 'Last Name',
    'registration.email': 'Email Address',
    'registration.phone': 'Phone Number',
    'registration.city': 'City',
    'registration.technicalBackground': 'Technical Background',
    'registration.currentField': 'Current Technical Field',
    'registration.techBackgroundPlaceholder': 'Describe your current technical experience (automotive, electronics, mechanics, etc.)',
    'registration.experience': 'Years of Technical Experience',
    'registration.selectExperience': 'Select experience level',
    'registration.experienceOptions.beginner': '0-1 years (Beginner)',
    'registration.experienceOptions.intermediate': '2-5 years (Intermediate)',
    'registration.experienceOptions.experienced': '5-10 years (Experienced)',
    'registration.experienceOptions.expert': '10+ years (Expert)',
    'registration.requirements': 'Requirements',
    'registration.canDrive': 'I have a valid driving license',
    'registration.freelancerStatus': 'I have freelancer status (auto-entrepreneur, micro-entreprise, etc.)',
    'registration.taxNumber': 'I have a tax identification number',
    'registration.bio': 'Professional Bio (Optional)',
    'registration.bioPlaceholder': 'Tell clients about your expertise and what makes you unique...',
    'registration.createAccount': 'Create Account & Continue to Bootcamp',
    'registration.terms': 'By creating an account, you agree to our Terms of Service and Privacy Policy',
    'registration.errors.required': 'This field is required',
    'registration.errors.freelancerRequired': 'Freelancer status is required to join our platform',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}