// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vocrgmrlqtfczfhfvkii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvY3JnbXJscXRmY3pmaGZ2a2lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMjMzMjUsImV4cCI6MjA3MzY5OTMyNX0.1R3yiamMFHr7JGHrCO4uKaWYtvfHXo-QpmNzTLfNRY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});